AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ENV:
    Type: String
    Description: environment variable
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description : Key pair that will be used
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ac80df6eff0e70b5
      KeyName: !Ref KeyPair
      Tags:
        - Key: Name
          Value: !Sub ${ENV}-my-ec2
      UserData: 
        Fn::Base64: !Sub
          |
          #!/bin/bash -xe
          sudo apt-get update
          sudo apt-get install -y nginx
          echo 'Ola mundo!' > /var/www/html/index.html