AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ENV:
    Type: String
    Description: environment variable
Resources:
  MeuBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ENV}-meu-bucket