AWSTemplateFormatVersion: 2010-09-09
Parameters:
  NAME:
    Type: String
    Description: Name of S3 bucket
Resources:
  MeuBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref NAME